Repository CS3219-AY2324S1/ay2324s1-course-assessment-g09, pull requests merged in 2023-09, with the labels that each got.

#3 Create landing page inclusive of create button
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/index.tsx
  frontend/tsconfig.json
  frontend/utils/sample-data.ts
Labels: enhancement

#5 Add _app.tsx
  frontend/pages/_app.tsx
Labels: bug

#11 Create Github Actions for a Telegram PR Notifier Bot
  .github/workflows/notifiy.telegram.yml
Labels: enhancement

#18 [Assignment 2b] Build SQL Database for User Management
  .github/workflows/node.js.yml
  .gitignore
  backend/question_repo/config/connectToDatabase.js
  backend/question_repo/controllers/questionsController.js
  backend/question_repo/model/question.js
  backend/question_repo/package-lock.json
  backend/question_repo/package.json
  backend/question_repo/server.js
  backend/user_manager/package-lock.json
  backend/user_manager/package.json
  backend/user_manager/queries.js
  backend/user_manager/server.js
  index.html
  package-lock.json
  package.json
Labels: enhancement

#20 Create skeleton Docker files for Containerisation
  backend/question_repo/Dockerfile
  backend/question_repo/docker-compose.yml
  backend/user_manager/Dockerfile
  backend/user_manager/docker-compose.yml
  frontend/Dockerfile
  frontend/components/InputField.tsx
  frontend/components/Question.tsx
  frontend/docker-compose.yml
  frontend/stores/questionsStore.js
Labels: enhancement

#23 Color mode toggle
  backend/question_repo/controllers/questionsController.js
  backend/question_repo/model/question.js
  backend/question_repo/server.js
  frontend/components/InputField.tsx
  frontend/components/Question.tsx
  frontend/components/Questions.tsx
  frontend/pages/index.tsx
  frontend/theme.js
  package-lock.json
  package.json
Labels: enhancement

#24 Improve Reliability of User Service
  backend/question_service/Dockerfile
  backend/question_service/config/connectToDatabase.js
  backend/question_service/controllers/questionsController.js
  backend/question_service/docker-compose.yml
  backend/question_service/model/question.js
  backend/question_service/package.json
  backend/question_service/server.js
  backend/user_manager/docker-compose.yml
  backend/user_manager/package-lock.json
  backend/user_manager/queries.js
  backend/user_manager/server.js
  backend/user_service/Dockerfile
  backend/user_service/README.md
  backend/user_service/docker-compose.yml
  backend/user_service/package-lock.json
  backend/user_service/package.json
  backend/user_service/src/server.js
  backend/user_service/src/usermanager.js
Labels: bug, documentation

#25 [Assignment 6] Draft Question Scraper Serverless Function
  backend/question_scraper/.gitignore
  backend/question_scraper/handler.js
  backend/question_scraper/package-lock.json
  backend/question_scraper/package.json
  backend/question_scraper/scraper.js
  backend/question_scraper/serverless.yml
  backend/question_service/Dockerfile
  backend/user_service/docker-compose.yml
Labels: enhancement

#28 Initial front and back end code for basic collab
  .gitignore
  backend/collaboration_service/server.js
  backend/communication_service/server.js
  backend/user_service/src/server.js
  frontend/components/VideoCall.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/collaboration.tsx
  frontend/pages/index.tsx
  package-lock.json
  package.json
Labels: enhancement

#26 [Assignment 2] Refactor Question Service in adherance to User Service's design pattern
  backend/question_service2/Dockerfile
  backend/question_service2/README.md
  backend/question_service2/docker-compose.yml
  backend/question_service2/package-lock.json
  backend/question_service2/package.json
  backend/question_service2/src/questionmanager.js
  backend/question_service2/src/server.js
  backend/user_service/README.md
  backend/user_service/docker-compose.yml
  backend/user_service/src/usermanager.js
Labels: enhancement

#27 User service UI
  backend/question_service/package-lock.json
  backend/user_service/src/server.js
  backend/user_service/src/usermanager.js
  frontend/components/Question.tsx
  frontend/components/Questions.tsx
  frontend/components/QuestionsHeader.tsx
  frontend/components/QuestionsInputField.tsx
  frontend/components/ToggleMode.tsx
  frontend/components/User.tsx
  frontend/components/UserHeader.tsx
  frontend/components/UserInputField.tsx
  frontend/components/Users.tsx
  frontend/pages/index.tsx
Labels: enhancement

#29 Drawer nav
  backend/user_service/src/usermanager.js
  frontend/components/Question.tsx
  frontend/components/Questions.tsx
  frontend/components/QuestionsInputField.tsx
  frontend/components/ToggleMode.tsx
  frontend/components/UserInputField.tsx
  frontend/pages/index.tsx
Labels: enhancement
