Repository CS3219-AY2324S1/ay2324s1-course-assessment-g09, pull requests merged in 2023-11, with the labels that each got.

#112 cancel match and error handling
  backend/matching_service/modelController.js
  backend/matching_service/server.js
  frontend/components/CodeEditor.tsx
  frontend/components/CreateCustomRoom.tsx
  frontend/components/History.tsx
  frontend/components/SaveHistoryButton.tsx
Labels: enhancement

#114 Refactor QuestionService for Brevity
  backend/question_service/src/connectdb.js
  backend/question_service/src/controllers/questionadmin.js
  backend/question_service/src/controllers/questionuser.js
  backend/question_service/src/server.js
  backend/question_service/src/utility/db.js
  backend/question_service/src/utility/questionmanager.js
Labels: enhancement

#116 Implement Elapsed Time and Prev/Next Qns
  development/docker-compose.yml
  frontend/pages/collaboration.tsx
Labels: enhancement

#126 Fix question addition bug
  frontend/components/CategoryCheckbox.tsx
  frontend/components/CategoryTag.tsx
  frontend/components/Question.tsx
  frontend/components/Questions.tsx
  frontend/components/QuestionsComponent.tsx
  frontend/components/QuestionsInputField.tsx
  frontend/pages/collaboration.tsx
  frontend/pages/dashboard.tsx
  frontend/pages/profile.tsx
  frontend/pages/signin.tsx
Labels: bug

#136 Refactor development/docker-compose.yml for readability and efficiency
  .gitignore
  development/.env
  development/docker-compose.yml
  kubernetes_deployment/authentication-service.yaml
  kubernetes_deployment/collaboration-service.yaml
  kubernetes_deployment/communication-service.yaml
  kubernetes_deployment/config.yaml
  kubernetes_deployment/frontend.yaml
  kubernetes_deployment/gateway-hpa.yaml
  kubernetes_deployment/gateway.yaml
  kubernetes_deployment/history-service.yaml
  kubernetes_deployment/matching-service.yaml
  kubernetes_deployment/mongo-history.yaml
  kubernetes_deployment/mongo.yaml
  kubernetes_deployment/postgres.yaml
  kubernetes_deployment/question-service.yaml
  kubernetes_deployment/rabbitmq.yaml
  kubernetes_deployment/user-service.yaml
Labels: enhancement

#139 Implement Edit User Field
  backend/authentication_service/src/controllers/authentication.js
  backend/user_service/src/controllers/user.js
  backend/user_service/src/utility/db.js
  frontend/components/CategoryCheckbox.tsx
  frontend/components/User.tsx
  frontend/components/UserComponent.tsx
  frontend/components/UserHeader.tsx
  frontend/components/UserInputField.tsx
  frontend/components/Users.tsx
  frontend/pages/dashboard.tsx
Labels: enhancement

#134 Fixed history not appearing bug
  backend/collaboration_service/server.js
  backend/communication_service/server.js
  backend/history_service/historyController.js
  backend/history_service/server.js
  backend/matching_service/modelController.js
  backend/matching_service/server.js
  backend/matching_service/socket.js
  frontend/components/CodeEditor.tsx
  frontend/components/CreateCustomRoom.tsx
  frontend/components/EndMatchButton.tsx
  frontend/components/History.tsx
  frontend/components/MatchButton.tsx
  frontend/components/Sockets/CollabSocketManager.ts
  frontend/components/VideoCall.tsx
  frontend/pages/collaboration.tsx
  frontend/pages/dashboard.tsx
  frontend/pages/profile.tsx
Labels: bug

#144 Stop watch, auto leave queue
  backend/collaboration_service/.env
  backend/collaboration_service/package-lock.json
  backend/collaboration_service/package.json
  backend/collaboration_service/server.js
  backend/matching_service/server.js
  backend/matching_service/socket.js
  frontend/components/CodeEditor.tsx
  frontend/components/EndMatchButton.tsx
  frontend/components/VideoCall.tsx
  frontend/pages/collaboration.tsx
  frontend/pages/dashboard.tsx
  frontend/pages/profile.tsx
Labels: bug, enhancement

#146 Saved question matched in history and synced match ending logic.
  backend/collaboration_service/server.js
  backend/communication_service/server.js
  backend/history_service/historyController.js
  backend/history_service/server.js
  backend/matching_service/socket.js
  frontend/components/CodeEditor.tsx
  frontend/components/EndMatchButton.tsx
  frontend/components/History.tsx
  frontend/components/Sockets/CollabSocketManager.ts
  frontend/components/VideoCall.tsx
  frontend/pages/collaboration.tsx
  frontend/pages/questionProgress.tsx
Labels: enhancement

#147 Fix Kubernetes Config Files
  gateway/nginx.conf
  kubernetes_deployment/frontend.yaml
  kubernetes_deployment/mongo-history.yaml
  kubernetes_deployment/postgres.yaml
  kubernetes_deployment/rabbitmq.yaml
Labels: enhancement

#148 Code editor duplicating edits
  backend/collaboration_service/server.js
  backend/matching_service/server.js
  frontend/components/CodeEditor.tsx
  frontend/components/VideoCall.tsx
Labels: bug

#150 Fix Gateway Server Config for Frontend
  gateway/nginx.conf
Labels: bug

#151 Various bugs fixed and progress bar implementation
  backend/collaboration_service/server.js
  backend/history_service/historyController.js
  backend/matching_service_rabbitmq/Dockerfile
  backend/matching_service_rabbitmq/README.md
  backend/matching_service_rabbitmq/custom-rabbitmq.conf
  backend/matching_service_rabbitmq/docker-compose.yml
  backend/matching_service_rabbitmq/package-lock.json
  backend/matching_service_rabbitmq/package.json
  backend/matching_service_rabbitmq/rabbitmqMatchingController.js
  backend/matching_service_rabbitmq/server.js
  backend/matching_service_rabbitmq/setup-rabbitmq-queue.sh
  frontend/components/CodeEditor.tsx
  frontend/components/EndMatchButton.tsx
  frontend/components/MatchButton.tsx
  frontend/pages/dashboard.tsx
  frontend/pages/questionProgress.tsx
Labels: bug, enhancement

#153 Update K8 Config to the Production Version
  .github/workflows/aws_deploy.yml
  kubernetes_deployment/ingress.yaml
  kubernetes_deployment/mongo-history-pv.yaml
  kubernetes_deployment/mongo-history.yaml
  kubernetes_deployment/mongo-pv.yaml
  kubernetes_deployment/mongo.yaml
  kubernetes_deployment/postgres-pv.yaml
  kubernetes_deployment/postgres.yaml
Labels: enhancement

#154 Fix visuals for history
  frontend/components/History.tsx
Labels: enhancement

#160 More bug fixed
  backend/collaboration_service/server.js
  frontend/components/CodeEditor.tsx
  frontend/components/MatchButton.tsx
  frontend/components/Sockets/CollabSocketManager.ts
  frontend/pages/collaboration.tsx
  frontend/pages/dashboard.tsx
  frontend/pages/questionProgress.tsx
Labels: bug

#167 Add color to end match button
  frontend/components/CodeEditor.tsx
  frontend/components/EndMatchButton.tsx
  frontend/components/VideoCall.tsx
  frontend/components/VideoComponent.tsx
  frontend/pages/collaboration.tsx
Labels: enhancement

#174 Provide confirmation for question delete
  frontend/components/Question.tsx
Labels: enhancement

#175 Improve UI for custom room
  frontend/components/CreateCustomRoom.tsx
  frontend/components/CustomRoomButton.tsx
  frontend/components/MatchButton.tsx
  frontend/pages/profile.tsx
Labels: enhancement

#178 Fix the bugs in question service
  frontend/components/Question.tsx
  frontend/pages/_app.tsx
  frontend/pages/assignment/index.tsx
  frontend/pages/profile.tsx
Labels: bug

#194 Fix question rendering bug in history
  backend/user_service/src/controllers/user.js
  frontend/components/History.tsx
Labels: bug

#202 Modified READMEs
  README.md
  backend/collaboration_service/README.md
  backend/communication_service/README.md
  backend/history_service/README.md
  backend/question_service/README.md
  backend/user_service/README.md
Labels: documentation
