Repository CS3219-AY2324S1/ay2324s1-course-assessment-g09, pull requests merged in 2023-10, with the labels that each got.

#31 Integrate collab service in collab tab
  frontend/components/ToggleMode.tsx
  frontend/components/VideoCall.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
Labels: enhancement

#32 Changed port from 3001 to 3000
  backend/collaboration_service/server.js
Labels: bug

#33 [Assignment 6] Implement Draft of Continuous Deployment to AWS ECR and Beanstalk
  .github/workflows/deploy.yml
  .github/workflows/node.js.yml
  backend/question_scraper/dbpusher.js
  backend/question_scraper/handler.js
  backend/question_scraper/index.js
  backend/question_scraper/package-lock.json
  backend/question_scraper/package.json
  backend/question_scraper/scraper.js
  backend/question_service/README.md
  backend/question_service/docker-compose.yml
  backend/question_service/package-lock.json
  backend/question_service/package.json
  backend/question_service/src/questionmanager.js
  backend/question_service/src/server.js
  backend/question_service2/docker-compose.yml
  backend/question_service2/package.json
  backend/question_service_old/Dockerfile
  backend/question_service_old/config/connectToDatabase.js
  backend/question_service_old/controllers/questionsController.js
  backend/question_service_old/docker-compose.yml
  backend/question_service_old/model/question.js
  backend/question_service_old/package-lock.json
  backend/question_service_old/package.json
  backend/question_service_old/server.js
  backend/user_service/README.md
  backend/user_service/docker-compose.yml
  backend/user_service/src/usermanager.js
  dockerrun.aws.json
  frontend/package-lock.json
  package-lock.json
  package.json
Labels: enhancement

#37 [Assignment 2] Refactor 'No User Found' behaviour for Question Service
  aws_deploy/docker-compose.yml
  backend/question_service/src/questionmanager.js
  dockerrun.aws.json
Labels: enhancement

#38 [Assignment 2] Implement CORS Support for UserService and QuestionService
  backend/question_service/package-lock.json
  backend/question_service/package.json
  backend/question_service/src/server.js
  backend/user_service/src/server.js
Labels: bug, enhancement

#39 Fix QuestionService Read Operation
  backend/question_service/src/questionmanager.js
Labels: bug, enhancement

#41 Integrate Frontend Service for Deployment
  .github/workflows/deploy.yml
  aws_deploy/docker-compose.yml
  frontend/docker-compose.yml
Labels: enhancement

#43 Refactor question service
  frontend/components/Question.tsx
  frontend/components/QuestionsInputField.tsx
Labels: enhancement

#45 Implement Modal and Error Border
  backend/question_service/src/questionmanager.js
  frontend/components/Question.tsx
  frontend/components/QuestionsInputField.tsx
  frontend/pages/index.tsx
  frontend/theme.js
Labels: enhancement

#47 Improve Modal Visibility & Implement Cancel Edit Button
  frontend/components/Question.tsx
  frontend/components/QuestionsInputField.tsx
  frontend/components/User.tsx
  frontend/components/UserInputField.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/index.css
Labels: bug, enhancement

#50 [Assignment 6] Serverless Function to pull Leetcode Qn
  backend/question_scraper/.gitignore
  backend/question_scraper/README.md
  backend/question_scraper/dbpusher.js
  backend/question_scraper/handler.js
  backend/question_scraper/index.js
  backend/question_scraper/package-lock.json
  backend/question_scraper/package.json
  backend/question_scraper/s_getQuestions.js
  backend/question_scraper/scraper.js
  backend/question_scraper/serverless.js
  backend/question_scraper/serverless.yml
  backend/question_service_old/Dockerfile
  backend/question_service_old/config/connectToDatabase.js
  backend/question_service_old/controllers/questionsController.js
  backend/question_service_old/docker-compose.yml
  backend/question_service_old/model/question.js
  backend/question_service_old/package-lock.json
  backend/question_service_old/package.json
  backend/question_service_old/server.js
  test
Labels: enhancement

#48 Remove Question Description and Add Clickable for Title
  frontend/components/Question.tsx
  frontend/components/QuestionsHeader.tsx
  frontend/package-lock.json
Labels: enhancement

#49 Complexity tag
  frontend/components/Question.tsx
  frontend/components/QuestionsInputField.tsx
  frontend/package-lock.json
Labels: bug, enhancement

#51 Implement Code Formatting for Javascript only
  frontend/.eslintrc.js
  frontend/components/CodeEditor.tsx
  frontend/components/VideoCall.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/collaboration.tsx
  frontend/pages/index.tsx
  package-lock.json
  package.json
Labels: enhancement

#53 Fix Deployment Issues + Finalise QuestionScraper (Lambda Fn)
  .github/workflows/deploy.yml
  aws_deploy/docker-compose.yml
  backend/question_scraper/README.md
  backend/question_scraper/scraper.js
  backend/question_scraper/serverless.js
  backend/question_scraper/serverless.yml
  backend/question_service/README.md
  backend/user_service/README.md
Labels: enhancement

#56 [Testing] Implement QuestionScraper Testing
  backend/question_scraper/package-lock.json
  backend/question_scraper/package.json
  backend/question_scraper/s_getQuestions.js
  backend/question_scraper/serverless.yml
  backend/question_scraper/src/scraper.js
  backend/question_scraper/src/serverless.js
  backend/question_scraper/test/scraper.test.js
  backend/question_scraper/test/setTestEnvVars.js
  frontend/Dockerfile
  frontend/package-lock.json
Labels: enhancement

#58 Fix double select complexity bug
  frontend/components/Question.tsx
  frontend/components/QuestionsInputField.tsx
  frontend/pages/index.tsx
Labels: bug

#61 Reallow previous UserService routing for back compatibility
  backend/user_service/src/server.js
Labels: enhancement

#62 Implement Landing Page
  frontend/components/Question.tsx
  frontend/components/QuestionsInputField.tsx
  frontend/pages/_app.tsx
  frontend/pages/assignment/index.css
  frontend/pages/assignment/index.tsx
  frontend/pages/dashboard.tsx
  frontend/pages/history.tsx
  frontend/pages/index.tsx
  frontend/pages/profile.tsx
  frontend/pages/questionProgress.tsx
Labels: enhancement

#65 Add Match Found Alert
  frontend/pages/profile.tsx
Labels: enhancement

#79 Improve Question Table
  frontend/components/CategoryTag.tsx
  frontend/components/Question.tsx
  frontend/components/QuestionsHeader.tsx
  frontend/pages/dashboard.tsx
  frontend/pages/profile.tsx
Labels: enhancement

#80 Provide different display between user and admin
  frontend/components/Question.tsx
  frontend/components/Questions.tsx
  frontend/components/QuestionsHeader.tsx
  frontend/components/UserHeader.tsx
  frontend/components/UserInputField.tsx
  frontend/pages/dashboard.tsx
  frontend/pages/profile.tsx
Labels: enhancement

#82 Fix infinite rendering calling questions bug
  frontend/components/Question.tsx
  frontend/components/Questions.tsx
  frontend/components/QuestionsInputField.tsx
  frontend/pages/dashboard.tsx
Labels: bug

#83 Dockers Authentication Related Services and Bug Fixes
  backend/authentication_service/.dockerignore
  backend/authentication_service/Dockerfile
  backend/authentication_service/src/controllers/apitauth.js
  backend/authentication_service/src/controllers/authentication.js
  backend/user_service/src/controllers/user.js
  backend/user_service/src/utility/db.js
  development/docker-compose.yml
  frontend/components/Question.tsx
  frontend/pages/assignment/index.tsx
  frontend/pages/dashboard.tsx
  frontend/pages/profile.tsx
  frontend/pages/signin.tsx
  frontend/pages/signup.tsx
  gateway/nginx.conf
Labels: bug, enhancement

#88 Refactor QuestionService to use HTTP verbs
  backend/question_scraper/package-lock.json
  backend/question_scraper/package.json
  backend/question_scraper/serverless.yml
  backend/question_scraper/src/scraper.js
  backend/question_scraper/src/serverless.js
  backend/question_service/README.md
  backend/question_service/docker-compose.yml
  backend/question_service/package-lock.json
  backend/question_service/src/connectdb.js
  backend/question_service/src/questionmanager.js
  backend/question_service/src/server.js
Labels: enhancement

#90 Update Serverless Function to fit the new QuestionService
  backend/question_scraper/README.md
  backend/question_scraper/serverless.yml
  backend/question_scraper/src/scraper.js
  backend/question_scraper/src/serverless.js
  backend/question_service/src/questionmanager.js
Labels: enhancement

#92 Add Random Question feature to QuestionManager
  backend/question_service/README.md
  backend/question_service/src/questionmanager.js
  backend/question_service/src/server.js
Labels: enhancement

#93 Fix category not resetting bug
  frontend/components/QuestionsInputField.tsx
Labels: bug

#97 Speed up Sign In / Sign Up and fix Log Out
  backend/authentication_service/src/controllers/authentication.js
  frontend/pages/profile.tsx
  gateway/nginx.conf
Labels: bug

#98 Fix Question Display Bug
  frontend/components/Question.tsx
  frontend/pages/profile.tsx
Labels: bug

#101 Add Support for Selecting Arbitrary Number of Question
  backend/question_scraper/src/scraper.js
  backend/question_service/README.md
  backend/question_service/src/connectdb.js
  backend/question_service/src/questionmanager.js
  backend/question_service/src/server.js
Labels: enhancement

#102 Beautify collab page
  frontend/components/CodeEditor.tsx
  frontend/components/VideoCall.tsx
  frontend/pages/collaboration.tsx
  frontend/pages/profile.tsx
Labels: enhancement

#103 Implement Filtering in question service
  frontend/components/Question.tsx
  frontend/components/Questions.tsx
  frontend/components/QuestionsComponent.tsx
  frontend/components/QuestionsHeader.tsx
  frontend/pages/dashboard.tsx
Labels: enhancement

#105 Improve UI on different screens
  frontend/components/LogoutButton.tsx
  frontend/components/Question.tsx
  frontend/components/Questions.tsx
  frontend/components/QuestionsComponent.tsx
  frontend/components/QuestionsHeader.tsx
  frontend/components/QuestionsInputField.tsx
  frontend/components/ToggleMode.tsx
  frontend/pages/collaboration.tsx
  frontend/pages/dashboard.tsx
  frontend/pages/index.tsx
  frontend/pages/profile.tsx
Labels: enhancement

#107 Fix horizontal overflow bug in modal
  frontend/components/CategoryTag.tsx
  frontend/components/MatchButton.tsx
  frontend/components/Question.tsx
  frontend/pages/collaboration.tsx
  frontend/pages/dashboard.tsx
Labels: bug

#109 Custom rooms
  backend/collaboration_service/.env
  backend/collaboration_service/server.js
  backend/communication_service/.env
  backend/communication_service/server.js
  backend/matching_service/.env
  backend/matching_service/model.js
  backend/matching_service/modelController.js
  backend/matching_service/publisher.js
  backend/matching_service/server.js
  backend/matching_service/socket.js
  frontend/components/CodeEditor.tsx
  frontend/components/CreateCustomRoom.tsx
  frontend/components/CustomRoomButton.tsx
  frontend/components/JoinCustomRoom.tsx
  frontend/components/MatchButton.tsx
  frontend/components/Sockets/MatchSocketManager.ts
  frontend/pages/profile.tsx
Labels: enhancement

#108 Fix bug where there is category error
  frontend/components/Question.tsx
Labels: bug

#111 Implement User Service to dashboard
  development/docker-compose.yml
  frontend/components/User.tsx
  frontend/components/UserHeader.tsx
  frontend/pages/dashboard.tsx
Labels: enhancement
